singer-io/tap-github

- tap_github.py
- tap_github/stargazers.json
This branch adds support for getting Stargazers from the specified repo. It includes a new optional header argument to the requests session. This is necessary for Stargazers in order to retrieve the `starred_at` property in the response. See: https://developer.github.com/v3/activity/starring/#list-stargazers
Unfortunately the API does not provide an option for querying based on `starred_at` so it will receive all of the Stargazers from the API every time. I am still storing `starred_at` to the state.
> Get all stargazers

- setup.py
- tap_github.py
- tap_github/stargazers.json
- Use singer-python 1.7.0
- Adds the config repo as a field on each Stargazer object. This is valuable if combining the data from multiple repos together in your destination.
- Updated PK for Stargazers
- Updated schema to represent new field
- Add stargazers.json to setup.py to fix PyPi package
> Stargazers fixes

- tap_github.py
The tap was not catching 401 responses (Auth Error).  This changes the tap so it looks for a 401 and raises an exception when it happens.
> Raise AuthException on 401 response

- tap_github/issues.json
Labels can be an array, labels can be null...and labels can be []! What a surprise!
This allows [] to come in.
> Allowing labels under issues to be a string

- tap_github.py
- tap_github/comments.json
This adds a comments stream for extracting [comments for a pull request](https://developer.github.com/v3/pulls/comments/#list-comments-on-a-pull-request).
Comments stream is added as a substream to pull_requests, similar to reviews. Included is support for validating dependency of pull_requests being selected.
TODO: Add support for metrics.comments_counter
> Add support for comments stream

- README.md
- tap_github.py
- tap_github/comments.json
This add issue comments as a selectable stream on the tap. The stream extracts all comments on issues and pull requests.
Uses the following endpoint: 
https://developer.github.com/v3/issues/comments/#list-comments-in-a-repository
> Add issue comments stream

- tap_github/issues.json
This resolves #36. The Assignee field on an issue can have an object and is not always `null`. This PR does not build out all of the properties and those should be added as needed in future issues.
I tested this locally with `target-stitch` and confirm that I am no longer seeing transform errors. Assignee object fields are now being filtered by the target since they are no yet outlined in the schema.
> Assignee can be more than null

- tap_github.py
While trying to use `tap-github` with a user whose permissions are _severely_ limited, we ran into the following problem:
https://circleci.com/gh/datamill-co/target-postgres/106
```
CRITICAL 'str' object does not support item assignment
Traceback (most recent call last):
File "/code/venv--tap-github/bin/tap-github", line 11, in <module>
load_entry_point('tap-github==1.3.1', 'console_scripts', 'tap-github')()
File "/code/venv--tap-github/lib/python3.7/site-packages/singer/utils.py", line 225, in wrapped
return fnc(*args, **kwargs)
File "/code/venv--tap-github/lib/python3.7/site-packages/tap_github.py", line 513, in main
do_sync(args.config, args.state, catalog)
File "/code/venv--tap-github/lib/python3.7/site-packages/tap_github.py", line 486, in do_sync
state = sync_func(stream_schema, …
```
> Fix: Status code 403 was hidden from users. Make failure obvious

- tap_github.py
GitHub’s /pulls endpoint doesn’t have a ?since filter, so instead we
check the updated_at values of each record imported. Since we have
sorted descending by this value, we can break out of the loop once we
have found the first updated_at value that is less than the bookmark
time.
Fixes #43
> Fix unnecessary re-fetching of pull request data

- tap_github.py
Fixes the tap to enable the sync of 'reviews'. The sub_streams dictionary currently only returns 'review_comments'. This change allows for it to return both 'reviews' and 'review_comments' so it can properly iterate through both substreams.
> Fix sub_stream to enable 'reviews'

- tap_github.py
Provides more diagnostics for #54.
> Improve error message when issue data structure is unexpected.

- tap_github/issues.json
This fixes the type sent of created_at, closed_at, and updated_at on the issues data.
> Treat issue dates as datetime type. Fixes #56

- tap_github.py
- tap_github/releases.json
(Will not load tag-only releases as seen in this repo's release tab)
Tested against: https://github.com/foosel/OctoPrint/releases
Output:
```
(tap-github) ~/p/tap-github> (tap-github-iTq1Y_tM) python tap_github.py -c config.json --properties properties.json
{"type": "STATE", "value": {}}
INFO Starting sync of repository: foosel/OctoPrint
{"type": "SCHEMA", "stream": "releases", "schema": {"selected": true, "type": ["null", "object"], "additionalProperties": false, "properties": {"_sdc_repository": {"type": ["string"]}, "id": {"type": ["null", "string"]}, "url": {"type": ["null", "string"]}, "html_url": {"type": ["null", "string"]}, "target_commitish": {"type": ["null", "string"]}, "tag_name": {"type": ["null", "string"]}, "name": {"type": ["null", "string"]}, "body": {"type": ["null", …
```
> Load GitHub's Releases

- tap_github.py
This change syncs the collection available at /repos/{}/pulls/{}/commits
These commits need to be synced in the case of workflows where PRs are squash merged, and to associate commits to the PRs that they were a part of
The schema is created by a slight modification of the commits schema
Select the pr_commits collection to be synced
- 
> Add support for PR commits to the GitHub Singer tap

- CHANGELOG.md
- setup.py
> bump to 1.7.0

- tap_github/commit_comments.json
- tap_github/issue_milestones.json
- tap_github/project_cards.json
- tap_github/project_columns.json
- tap_github/projects.json
- tap_github/pull_request_reviews.json
I removed the date-time format section in the JSON files. Fields such as url, project_url, and others are string fields so it crashes the application that I use because it isn't the right format.
> Remove date-time format for String fields such as url, content_url, project_url, etc.

- CHANGELOG.md
- setup.py
> Bump version to 1.7.1

- .gitignore
- tap_github.py
Fixes #78 
`pr_commits` were originally added as a sub_stream to `pull_requests` in #67 . However, it looks like it was unintentionally removed from `pull_requests'` sub_stream in [this PR](https://github.com/singer-io/tap-github/commit/bddf69424917b13174cfd203a6cde7e6805ffdb4#diff-f26d495b1346c44875efc276d691e2fcL850). This PR simply adds it back in.
- I ran this locally and it completed successfully while syncing the pr_commits. 
- WW3
> re-add pr_commits as sub_stream of pull_requests

- CHANGELOG.md
- setup.py
Version bump for #81 
- Ran tap with #81 and confirmed that we get records for `pr_commits`
- Low
- revert #81 and bump the version
> Bump to v1.8.1, update changelog

- CHANGELOG.md
- setup.py
- tap_github/projects.json
- tap_github/pull_request_reviews.json
Fix [issue 83](https://github.com/singer-io/tap-github/issues/83) by removing `format: date-time` from `html_url` field in `projects.json` and `pull_request_url` and `href` fields in `pull_request_reviews.json`.
Removed format param, ran discovery and sync. No issues.
Low - very minor change to field in JSON schema.
Revert to 1.8.1
> Fix issue 83, projects.json and pull_request_reviews.json

- .circleci/config.yml
Run the json validator against schemas in the checkout code rather than the virtual environment.
- 
- 
> stitch-validate-json checkout code not venv

- tap_github/schemas/pull_requests.json
Adds the `base` node to the `pull_requests.json` definition. It includes the following new fields:
- `base.ref` _(so now we can tell where pull requests are targeted)_
- `base.label`
- `base.sha`
- `base.repo.id`
- `base.repo.name`
- `base.repo.url`
My test produced the following added result:
```
...
{
"base":{
"label":"felipefrancisco:master",
"ref":"master",
"sha":"0d77a1034b9dbf08b8f91369a65c13b9c726c722",
"repo": {
"id":215760822.0,
"name":"analytics",
"url":"https://api.github.com/repos/felipefrancisco/analytics"
}
}
}
...
```
The fields added to the `pull_requests.json` is directly matching the documentation provided in Github's official docs for the List Pull Requests endpoint:
https://docs.github.com/en/rest/reference/pulls#list-pull-requests
- Follow the initial configuration …
> Add support for base details, such as 'ref', 'repo', 'label' and 'sha'

- tap_github/__init__.py
- tests/test_github_discovery.py
- tests/unittests/test_rate_limit.py
TDL-7674: Handle API rate limit exceeded
- Explicitly added wait time more than 10 minutes and checked if exception occurred
- Explicitly added wait time less than 10 minutes and checked if tap waits for that time
- 
> TDL-7674: Added support for handling API rate limit exceeded

- tap_github/__init__.py
- tests/unittests/test_formatting_dates.py
TDL-13116: Formatting dates should not emit a stack-trace
- Explicitly made "due_on"= None and checked if tap fetched that data
- Explicitly given bookmark < "due_on" and checked if tap fetched that data
- Explicitly given bookmark > "due_on" and checked if tap not fetched that data
- 
> TDL-13116: Added code change for formatting none dates

- tap_github/__init__.py
- tests/unittests/test_key_error.py
TDL-13117: Avoid KeyError on calls to retrieve data from the dictionary
- Manually removed deselected "slug" and "user" from catalog file and checked if data was fetched
- 
> TDL-13117: Added support for KeyError on fetching data from dictionary

- tap_github/__init__.py
- tests/unittests/test_exception_handling.py
- tests/unittests/test_verify_access.py
TDL-13115: do_discover should check permissions of the token given
- Intentionally made some credentials with limited permissions and checked if the tap throws error.
- 
> TDL-13115: Added support for checking credentials during discovery mode

- tap_github/__init__.py
- tests/unittests/test_sub_streams_selection.py
TDL-13660: Main streams must be selected while collecting data for sub-streams
- Manually selected sub_streams without main stream and checked if the error was generated.
- 
> TDL-13660: Added support for checking if main stream is selected when fetching sub_stream data

- tap_github/__init__.py
- tests/unittests/test_verify_access.py
Modified error message when the personal repository is provided.
- 
- 
> TDL-13115: Modified some error messages

- README.md
- config.sample.json
- tap_github/__init__.py
- tests/test_github_start_date.py
TDL-13624 : Respect start_date(#119) fixes
-  Added start_date in required config parameter.
-  Added start_date in config-sample of README.md and config.sample.json file.
-  Removed mention of the 'pull_request_reviews" stream from start date integration test as a stream is deleted.([#117](https://github.com/singer-io/tap-github/pull/117))
-  Verified that error is raised if start_date is not provided in config.
-  No risk
> TDL-13624: Make start date required field, add start_date in readme and sample config

- CHANGELOG.md
- setup.py
Version bump for 
* #113 
* #114
* #118 
* #121 
* #117
* #123 
* Handle rate limiting [#113](https://github.com/singer-io/tap-github/pull/113)
* Handle `None` date times in the Issue Milestones Stream [#114](https://github.com/singer-io/tap-github/pull/114)
* Change the Stargazers Stream to be Full Table replication [#118](https://github.com/singer-io/tap-github/pull/118)
* Log an error message if an organization cannot be found [#121](https://github.com/singer-io/tap-github/pull/121)
* Bump `singer-python` dependency to `v5.12.1` [#117](https://github.com/singer-io/tap-github/pull/117)
* Remove stream `pull_request_reviews` [#117](https://github.com/singer-io/tap-github/pull/117)
* Add API access check to discovery mode [#123](https://github.com/singer-io/tap-github/pull/123)
- revert …
> Bump to v1.10.0, update changelog

- tap_github/__init__.py
- tests/unittests/test_exception_handling.py
This PR highlights and fixes an edge case in `raise_for_error()`
- 
- 
> Raise an exception instead of swallowing an error

- tests/base.py
- tests/test_github_start_date.py
Resolve Start Date test case failure
- For 'events' stream the API will only fetch the data of the past 90 days only.
- Use API to generate 'events' data and made start dates dynamic ie. 1st start date `today() - 1 days` and 2nd start date `today() - 4 days`.
- 
- 
> Resolve Start Date test case failure

- setup.py
- tap_github/__init__.py
- tests/unittests/test_extract_repos_from_config.py
- tests/unittests/test_get_all_repos.py
Re-submitting #141 from a branch of master for [TDL-6330](https://jira.talendforge.org/browse/TDL-6330)
- See #141 
- 
> Re-submitting PR #141 (All repos for an organization)

- tap_github/schemas/teams.json
TDL-16550: Add support of object in "parent" field for teams
- Added "object" datatype for the "parent" field in the "teams" stream
NOTE: Created parent-child teams from another account and verified the code change using Import API from the stitch UI
- 
- 
> TDL-16550: Add support of object in "parent" field for teams - (Copy of PR #107)

- .circleci/config.yml
- README.md
- config.sample.json
- tap_github/__init__.py
- tests/unittests/test_exception_handling.py
- tests/unittests/test_timeout.py
- tests/unittests/test_verify_access.py
TDL-16349: Add request timeout
- Use default timeout of 300 seconds if the user does not enter the preferred timeout value
- 
- 
> TDL-16349: Add request timeout

- .circleci/config.yml
- .gitignore
- README.md
- setup.py
- tap_github/__init__.py
- tests/base.py
- tests/test_github_all_fields.py
- tests/test_github_automatic_fields.py
- tests/test_github_bookmarks.py
- tests/test_github_start_date.py
- tests/unittests/test_exception_handling.py
- tests/unittests/test_extract_repos_from_config.py
- tests/unittests/test_formatting_dates.py
- tests/unittests/test_get_all_repos.py
- tests/unittests/test_key_error.py
- tests/unittests/test_rate_limit.py
- tests/unittests/test_start_date_bookmark.py
- tests/unittests/test_sub_streams_selection.py
- tests/unittests/test_verify_access.py
Re-submitting PR #140 from a branch on singer-io master for [TDL-14049](https://jira.talendforge.org/browse/TDL-14049)
- see #140 
- 
> Re-submitting PR #140 (Add additional base test suite tests)

- tap_github/__init__.py
- tap_github/schemas/team_members.json
- tests/base.py
- tests/test_github_automatic_fields.py
Fixes bug for `team_members` stream as per [TDL-17507](https://jira.talendforge.org/browse/TDL-17507)
- ran tap locally w/ `singer-check-tap` and `target-stitch --dry-run`
- circle tests passing
- primary keys change for `team_members` stream
> Fix team_members stream PK

- README.md
- config.sample.json
- tap_github/client.py
- tap_github/streams.py
- tests/test_github_sync.py
- tests/unittests/test_custom_domain.py
- tests/unittests/test_stream.py
- tests/unittests/test_verify_access.py
- Added support of custom domain.
- Added unit test case for the changes.
**Note**: Build is failing because config parameter `base_url` is missing.
- Verify that if a custom domain is provided in the config then that domain is being used by tap to call the REST API.
- Verify that if a custom domain is not provided in the config then that default domain is being used by tap to call the REST API.
- 
> TDL-5961 Support of custom domain

- tap_github/streams.py
- tests/test_github_interrupted_sync.py
- tests/unittests/test_sync_endpoint.py
- Added query param for the `pull_requests` stream.
- An updated unit test case for the `pull_requests` stream.
- 
- 
> Tdl 20302 add query param for pull requests

- tap_github/client.py
- tests/unittests/test_rate_limit.py
- Added logic to raise exception if `X-RateLimit-Reset` is not found in the response header.
- Added unit test case to validate the same scenario.
- 
- 
> TDL-20336 custom domain which are not created as a part of Github results into key error

- tap_github/sync.py
- tests/unittests/test_get_streams_and_state_translate.py
- Added logic to return the existing state if all existing repos are unselected for the next sync.
- Added unit test to verify the same.
- 
- 
> TDL 20339 handle empty bookmark if all repos unselected for next sync.

- CHANGELOG.md
- setup.py
- tap_github/client.py
- tests/test_github_bookmarks.py
- tests/test_github_pagination.py
- tests/test_github_start_date.py
This PR handles Github's error response when we request the commits from an empty repository.
The change is scoped specifically to the `Commits` stream because this is the only stream I've observed this behavior for.
- Ran the tap in discovery mode and sync mode
- Low. This is a blocker that's easy to reproduce and this change allows the tap to run.
> TDL-22816 allow discovery of commitless repos

- CHANGELOG.md
- setup.py
- tap_github/client.py
- tests/unittests/test_rate_limit.py
GitHub has a 5000 API requests limit per hour, once the API request rate limit is reached the TAP throws the below exception - 
```
2023-05-11 10:14:56,025Z    tap - CRITICAL API rate limit exceeded, please try after 1854 seconds.
2023-05-11 10:14:56,026Z    tap - Traceback (most recent call last):
2023-05-11 10:14:56,026Z    tap -   File "tap-env/bin/tap-github", line 33, in <module>
2023-05-11 10:14:56,026Z    tap -     sys.exit(load_entry_point('tap-github==2.0.1', 'console_scripts', 'tap-github')())
2023-05-11 10:14:56,026Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 229, in wrapped
2023-05-11 10:14:56,026Z    tap -     return fnc(*args, **kwargs)
2023-05-11 10:14:56,026Z    tap -   File …
```
> TDL-22921 Fix the api limit error

- CHANGELOG.md
- setup.py
- tap_github/client.py
Implemented the fixture for the secondary rate limit.
link - https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#secondary-rate-limits
- Tested locally and observed tap pauses for the respective `Retry-After` seconds.
- 
> Handle the secondary rate limit

- tap_github/schemas/releases.json
The field `discussion_url` in `releases` schema is incorrectly defined as `date-time` causing some issues in the extraction.
- Manually tested with Meltano.
- 
> Fix incorrect format of discussion_url field in releases schema

- CHANGELOG.md
- setup.py
- tap_github/schemas/commits.json
- tap_github/schemas/pr_commits.json
- tests/test_github_all_fields.py
See PR title. updates all_fields known missing fields to remove these.
- tested w/ client connection; ran all fields test (passing)
- confusion for people who had those fields selected
> TDL-239782 Remove `files` and `stats` fields from commit-related schemas

- CHANGELOG.md
- setup.py
- tap_github/discover.py
Python versions prior to 3.6 do not maintain insertion order for dictionaries. If the root object of metadata is not the first element in the metadata list, the `key_properties` field in the schema will not be set correctly.
This change will allow all python versions to grab the correct value for the PK.
- Schema includes the correct key_properties/PK for all streams
- If the PK was not in the schema for a stream, this will change the PK. Tables in the destination will need to updated to handle the new PK.
> TDL-24380 - Don't rely on dictionary order to grab PKs

- CHANGELOG.md
- setup.py
- tap_github/schemas/events.json
- Fixes below error ([TDL-24898](https://jira.talendforge.org/browse/TDL-24898)):
`2024-02-20 21:15:43,447Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code -15. Target failed with code 1 and error message: "Error persisting data to Stitch: 400: {'error': 'Record 0 for table events did not conform to schema:\n#: #: no subschema matched out of the total 2 subschemas\n#/payload: #: no subschema matched out of the total 2 subschemas\n#/payload/issue: #: no subschema matched out of the total 3 subschemas\n#/payload/issue/labels: #: no subschema matched out of the total 2 subschemas\n#/payload/issue/labels/1: #: no subschema matched out of the total 2 subschemas\n#/payload/issue/labels/1/url: #: no subschema matched out of the total 2 …
> remove uri format from the events url field

- CHANGELOG.md
- setup.py
- tap_github/streams.py
- tap_github/sync.py
- tests/test_github_all_fields.py
- tests/test_github_bookmarks.py
- tests/test_github_interrupted_sync.py
- tests/test_github_interrupted_sync_add_stream.py
- tests/test_github_interrupted_sync_remove_stream.py
- tests/test_github_pagination.py
- tests/test_github_start_date.py
- tests/unittests/test_get_streams_and_state_translate.py
- tests/unittests/test_stream.py
- tests/unittests/test_sync_endpoint.py
Tap-github supports multiple repositories. The previous bookmark format for tap was:
`{bookmarks {repository {stream_name ...}}}`
In order to support stream level resets, we need to switch the bookmark format to:
`{bookmarks {stream_name {repository ...}}}`
This pr update the `translate_state` function to convert old bookmarks into the new state. New connections will have the new format automatically. 
- Created a connection on master with the old bookmark format. Switched to this branch, ran another sync and checked that the format changed. Then, I deselected all the repos in use and added a new repo to make sure state is not dropped.
- in 2018 multiple repo support was added [here](https://github.com/singer-io/tap-github/pull/33), and bookmarks were converted from `{bookmarks …
> Tdl 26656 transform state

- CHANGELOG.md
- setup.py
- tap_github/streams.py
- tests/base.py
- tests/test_github_all_fields.py
- tests/test_github_sync.py
- tests/unittests/test_get_streams_and_state_translate.py
- tests/unittests/test_stream.py
- tests/unittests/test_sync.py
- tests/unittests/test_sync_endpoint.py
Github [has sunset](https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/) the product functionality behind these streams and the API endpoints are now non-functional. This PR removes the affected streams and removes them from tests where applicable. Other tests are commented out as they may prove useful for revision with other child streams.
- 
- 
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code
> SAC-27669: Remove Sunset Projects, ProjectCards, and ProjectColumns streams

- .circleci/config.yml
- CHANGELOG.md
- setup.py
- tap_github/client.py
- tap_github/streams.py
- tests/unittests/test_exception_handling.py
- Upgrade python version in circleci build to 3.12 
- Unpin pylint dev dependency
- Fix new pylint errors
- 
- 
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code
> Use python 3.12 in circleci
