setup.py, tap_github.py
Sample output:
```
INFO METRIC: {"tags": {"status": "succeeded", "http_status_code": 200, "endpoint": "commits"}, "metric": "http_request_duration", "type": "timer", "value": 0.27280640602111816}
INFO METRIC: {"tags": {"status": "succeeded", "http_status_code": 200, "endpoint": "commits"}, "metric": "http_request_duration", "type": "timer", "value": 0.09011340141296387}
INFO METRIC: {"tags": {"status": "succeeded", "http_status_code": 200, "endpoint": "commits"}, "metric": "http_request_duration", "type": "timer", "value": 0.2071216106414795}
INFO METRIC: {"tags": {"status": "succeeded", "http_status_code": 200, "endpoint": "commits"}, "metric": "http_request_duration", "type": "timer", "value": 0.09051299095153809}
INFO METRIC: {"tags": {"status": "succeeded", "http_status_code": 200, …
```
=> Use new metrics format

tap_github/pull_requests.json
I am adding more fields to the JSON of pull requests to get the merged at and user info
=> Adding fields to pull requests

tap_github.py, tap_github/reviews.json
- Adds support for dependent "sub-streams".  When a sub-stream is selected to sync, there is a check that makes sure it's parent stream is also selected.  If it is not, a Dependency Exception is thrown.
- Adds reviews stream -- it is a sub stream of pull requests.
=> Adding reviews stream

tap_github.py
changing singer.Transformer() to singer.transform to avoid excess logging
=> reverting transformer change to avoid excess loggin

tap_github.py
tap was not counting reviews records
=> fix reviews counter

tap_github/reviews.json
I am adding 5 more fields to reviews, including the url for the PR so it can be joined back to pull_requests
=> Adding the rest of the fields for reviews

setup.py, tap_github.py
* Write and use state according to the updated singer spec.
* Write metadata in a simpler way and use it to allow for property selection.
=> State and Metadata Updates

tap_github/issues.json
This adds labels to the issues property so people who use labels on their PRs can query for them
=> Adding the labels property to the issues

tap_github/issues.json
=> Fix null fields in Issues schema

tap_github/pull_requests.json
This PR adds fields for Pull Request labels to the existing `pull_requests.json` schema file.
=> Add PR label fields

CHANGELOG.md, setup.py
=> bump to 1.6.0

CHANGELOG.md, setup.py
Releases https://github.com/singer-io/tap-github/pull/75
- 
- 
=> bump to 1.8.0

.circleci/config.yml, setup.py, tap_github/__init__.py, tests/base.py, tests/test_github_discovery.py, tests/test_github_projects_streams.py
Fixes a bug where the incorrect endpoint was being hit for the Project Cards stream.
- Synced the fixed streams and confirmed the appropriate records came out.
- 
=> Fix support for Project Cards stream

tap_github/__init__.py, tap_github/schemas/issue_events.json, tests/base.py, tests/test_github_issue_events_stream.py
added issue events stream
added test to check that issue_events records are syncing
made sure that added_to_project, moved_columns_in_project, removed_from_project, converted_note_to_issue
- added test to check that discovery worked and that sync for issue_events worked, it passed
- low
=> Issue events

CHANGELOG.md, setup.py
minor version bump for tap-github
- none
- low
=> minor version bump, added changelog entry

CHANGELOG.md, setup.py
Version bump for #102 
- See #102 
- See #102 
- revert #102 and bump the version
=> Bump to v1.9.1, update changelog

CHANGELOG.md, setup.py
Version bump and changelog for #109 
- Ran through the changes from #109 and manually inspected their effect
- Low, it's a safe schema addition
- revert #109, release new patch version
=> Version 1.9.2 and changelog

tap_github/__init__.py, tests/unittests/test_stargazers_full_table.py
TDL-13661: Remove the query parameters for 'Stargazers' stream
- 
- 
=> TDL-13661: Changed Stargazers as full table stream

tap_github/__init__.py, tests/unittests/test_exception_handling.py, tests/unittests/test_formatting_dates.py, tests/unittests/test_key_error.py, tests/unittests/test_stargazers_full_table.py, tests/unittests/test_verify_access.py
TDL-13115: Check minimal permission in discovery mode.
- 
- 
=> TDL-13115: Added code change for checking minimal permissions

setup.py, tests/test_github_pagination.py
https://jira.talendforge.org/browse/TDL-15050
We were getting generator objects instead of the pk values, fix that
- 
- 
=> update generator to tuple of pk values

setup.py, tap_github/__init__.py, tests/unittests/test_exception_handling.py, tests/unittests/test_formatting_dates.py, tests/unittests/test_key_error.py, tests/unittests/test_rate_limit.py, tests/unittests/test_start_date_bookmark.py, tests/unittests/test_sub_streams_selection.py, tests/unittests/test_verify_access.py
re-submitting #142 from branch of master
- see #142 
- 
=> Re-submitting PR #142 (Improve Rate Limiting and Retry Logic)

CHANGELOG.md, setup.py
This is to take care of support of object in "parent" field for teams 
- 
- 
=> Bump version 1.10.1

CHANGELOG.md, setup.py
- Implementation of Wild card for Repository Name
- Additional Test Coverage
- Small Bug fixes
- 
- 
=> Bump version for implementing wild card in Github Repository Name

CHANGELOG.md, setup.py
Fix primary key for team_members
- 
- 
=> Bump version to fix team_members primary key

tap_github/sync.py
(write a short description or paste a link to JIRA)
- 
- 
=> Updated currently syncing for teams streams.

CHANGELOG.md, setup.py
major bump version 2.0.0
- 
- 
=> major bump version 2.0.0

CHANGELOG.md, setup.py, tap_github/client.py
Handle the corner-case scenario for this PR - #191 
- 
- Low
=> Recursively call the function if `Retry-After` has the value greater than 0

CHANGELOG.md, setup.py
- #196 
- setup and changelog modified
- As the test account is missing the record with the discussion_url field, therefore, temporarily added the date-time format in the upload_url field and tested.
- low
=> Minor bump version to fix the bug 

setup.py, tests/base.py, tests/test_github_all_fields.py, tests/test_github_automatic_fields.py, tests/test_github_bookmarks.py, tests/test_github_pagination.py, tests/test_github_parent_child_independednt.py, tests/test_github_start_date.py, tests/test_github_sync.py, tests/unittests/test_stream.py
https://qlik-dev.atlassian.net/browse/SAC-27925
- bump dependency versions for compliance
- 
- 
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code
=> SAC-27925: dependency bumps for compliance
